// you cannot set the property of all by using let p = document.querySelectorAll('p') then p.style.color = "green", it will give an error.

// to do it you would have to manually loop. so let par = document.querySelectorAll('p'), you can do it in the js file as well(did here)
let par = document.querySelectorAll('p')  

for(let p of par){
    p.style.color = "green"
    p.style.fontSize = '15px'
}

// to make this work you have to put the script tag in html at the end of the body(at least this is one approach). This way the script wont run until all of the content is generated by the browser, if it is put first, the script will run first without the content being on the page.